const sampleData = {
  products: [
    {
      name: 'Hikvision 8 Channel DVR',
      slug: 'hikvision-8-channel-dvr',
      category: 'Video Recorders',
      description: '8-channel DVR with real-time recording and mobile access',
      images: [
        '/images/sample-products/p1-1.jpg',
        '/images/sample-products/p1-2.jpg',
      ],
      price: 6999.0,
      brand: 'Hikvision',
      rating: 4.7,
      numReviews: 14,
      stock: 7,
      isFeatured: true,
      banner: 'banner-1.jpg',
    },
    {
      name: 'Ubiquiti NanoStation M5 Wireless Antenna',
      slug: 'ubiquiti-nanostation-m5',
      category: 'Wireless Antennas',
      description: 'High-performance outdoor CPE with 5GHz 150+ Mbps throughput',
      images: [
        '/images/sample-products/p2-1.jpg',
        '/images/sample-products/p2-2.jpg',
      ],
      price: 8499.0,
      brand: 'Ubiquiti',
      rating: 4.8,
      numReviews: 9,
      stock: 4,
      isFeatured: false,
      banner: 'banner-2.jpg',
    },
    {
      name: 'TP-Link Archer AX20 Wi-Fi 6 Router',
      slug: 'tp-link-archer-ax20-wifi6-router',
      category: 'Networking Routers',
      description: 'Next-gen Wi-Fi 6 router with dual-band speeds and WPA3 security',
      images: [
        '/images/sample-products/p3-1.jpg',
        '/images/sample-products/p3-2.jpg',
      ],
      price: 4499.0,
      brand: 'TP-Link',
      rating: 4.5,
      numReviews: 23,
      stock: 12,
      isFeatured: true,
      banner: 'null',
    },
    {
      name: 'Dahua 4MP Bullet IP Camera',
      slug: 'dahua-4mp-bullet-ip-camera',
      category: 'CCTV Cameras',
      description: '4MP outdoor bullet camera with night vision and PoE support',
      images: [
        '/images/sample-products/p4-1.jpg',
        '/images/sample-products/p4-2.jpg',
      ],
      price: 2899.0,
      brand: 'Dahua',
      rating: 4.6,
      numReviews: 17,
      stock: 0,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'Netgear GS308 8-Port Gigabit Switch',
      slug: 'netgear-gs308-8-port-switch',
      category: 'Network Switches',
      description: 'Reliable, plug-and-play 8-port gigabit switch for home/office use',
      images: [
        '/images/sample-products/p5-1.jpg',
        '/images/sample-products/p5-2.jpg',
      ],
      price: 2999.0,
      brand: 'Netgear',
      rating: 4.4,
      numReviews: 11,
      stock: 10,
      isFeatured: false,
      banner: null,
    },
    {
      name: 'MikroTik hAP ac² Dual Band Router',
      slug: 'mikrotik-hap-ac2-router',
      category: 'Networking Routers',
      description: 'Compact dual-band router with powerful management features',
      images: [
        '/images/sample-products/mikrotik-p6-1.jpg',
        '/images/sample-products/mikrotik-p6-2.jpg',
      ],
      price: 5999.0,
      brand: 'MikroTik',
      rating: 4.3,
      numReviews: 7,
      stock: 6,
      isFeatured: true,
      banner: null,
    },
  ],
};

export default sampleData;